pzpr = require('./pzpr/core.js');
pzpr.Candle = require('../node_modules/pzpr-canvas/dist/candle.js');
pzpr.env = require('./pzpr/env.js');
pzpr.lang = require('./pzpr/lang.js');
require('./pzpr/event.js');
pzpr.common = require('./pzpr/common.js');
pzpr.classmgr = require('./pzpr/classmgr.js');
pzpr.variety = require('./pzpr/variety.js');
pzpr.parser = require('./pzpr/parser.js');
pzpr.util = require('./pzpr/util.js');
pzpr.Puzzle = require('./puzzle/Puzzle.js');
pzpr.Puzzle.prototype.Config = require('./puzzle/Config.js');
pzpr.classmgr.makeCommon(require('./puzzle/Address.js'));
pzpr.classmgr.makeCommon(require('./puzzle/Piece.js'));
pzpr.classmgr.makeCommon(require('./puzzle/PieceList.js'));
pzpr.classmgr.makeCommon(require('./puzzle/Board.js'));
pzpr.classmgr.makeCommon(require('./puzzle/BoardExec.js'));
pzpr.classmgr.makeCommon(require('./puzzle/GraphBase.js'));
pzpr.classmgr.makeCommon(require('./puzzle/LineManager.js'));
pzpr.classmgr.makeCommon(require('./puzzle/AreaManager.js'));
pzpr.classmgr.makeCommon(require('./puzzle/Graphic.js'));
pzpr.classmgr.makeCommon(require('./puzzle/MouseInput.js'));
pzpr.classmgr.makeCommon(require('./puzzle/KeyInput.js'));
pzpr.classmgr.makeCommon(require('./puzzle/Encode.js'));
pzpr.classmgr.makeCommon(require('./puzzle/FileData.js'));
pzpr.classmgr.makeCommon(require('./puzzle/Answer.js'));
pzpr.classmgr.makeCommon(require('./puzzle/Operation.js'));
pzpr.classmgr.makeCommon(require('./variety-common/Graphic.js'));
pzpr.classmgr.makeCommon(require('./variety-common/KeyInput.js'));
pzpr.classmgr.makeCommon(require('./variety-common/MouseInput.js'));
pzpr.classmgr.makeCommon(require('./variety-common/Answer.js'));
pzpr.classmgr.makeCommon(require('./variety-common/BoardExec.js'));
pzpr.classmgr.makeCommon(require('./variety-common/Encode.js'));
pzpr.classmgr.makeCommon(require('./variety-common/FileData.js'));

module.exports = pzpr;
